=== hynekmusil/hr-help/component/article/model-article.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://formax.cz/ns/aricle"
    xmlns="http://formax.cz/ns/aricle"
    elementFormDefault="qualified"    
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" 
        schemaLocation="http://www.w3.org/2001/xml.xsd"/>
    
    <xs:element name="article" type="block"/>
    
    <xs:complexType name="block">
        <xs:sequence>
            <xs:element ref="h" minOccurs="0"/>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="p"/>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    
    <xs:group name="block">
        <xs:choice>
            <xs:element ref="p"/>
        </xs:choice>
    </xs:group>
    
    <xs:element name="h" type="xs:string"/>
    
    <xs:element name="p">
        <xs:complexType mixed="true">
            <xs:choice minOccurs="0" maxOccurs="unbounded">
               <xs:group ref="inline"/>
            </xs:choice>
            <xs:attribute name="class"/>
        </xs:complexType>
    </xs:element>
    
    <xs:group name="inline">
        <xs:choice>
            <xs:element ref="br"/>
            <xs:element ref="a"/>
            <xs:element ref="email"/>
            <xs:element ref="img"/>
            <xs:element ref="strong"/>
        </xs:choice>
    </xs:group>
    
    <xs:element name="br">
        <xs:complexType/>
    </xs:element>
    
    <xs:element name="a">
        <xs:complexType mixed="true">
            <xs:attribute name="href"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="email">
        <xs:complexType mixed="true">
            <xs:attribute name="href"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="img">
        <xs:complexType>
            <xs:attribute name="href"/>
            <xs:attribute name="src"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="strong" type="xs:string"/>
    
</xs:schema>

=== hynekmusil/hr-help/data/article-aktualne.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns="http://formax.cz/ns/article" 
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://formax.cz/ns/article ../component/article/model-article.xsd"
>
 <h>Aktuálně</h>
 <p>Dne <strong>10.1.2010</strong> spouštíme portál HR-Help.cz, který Vám pomůže řešit některé body z HR problematiky. Nabízíme tímto velmi zajímavá IT řešení na HR procesy.
  První funkční aplikace pro Vás bude <a href="/sluzby/pruzkum-spokojenosti-zamestnancu/">Průzkum spokojenosti zaměstnanců</a>. Varianta zdarma Vám umožní zadat až 20 otázek a vybrat k nim ze seznamu odpovědí. Zároveň jsou k dispozici další 3 otázky pro kategorizaci odpovědí. Vyhodnocení poté probíhá na sloupcových grafech.</p>
 <p>Jednotlivé grafy lze uložit jako obrázky, více informací naleznete v <a href="/sluzby/pruzkum-spokojenosti-zamestnancu/priklady/">příkladech</a> k dané službě.</p>
 <p> Zároveň jsme udělali vzorový výpočet, který by Vám měl usnadnit rozhodování, zda-li je tato služba pro Vás zajímavá. Podrobný výpočet naleznete <a href="/sluzby/pruzkum-spokojenosti-zamestnancu/#vypocet">zde</a>.</p>
</article>

=== hynekmusil/hr-help/data/article-jak_zacit.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns="http://formax.cz/ns/article" 
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://formax.cz/ns/article ../component/article/model-article.xsd"
>
 <h>Jak začít</h>
 <p>Aplikace je připravena tak, aby veškeré ovládaní a nastavení mohli provádět sami za použití svého přihlašovacího jména a hesla.<br/><br/>
  Tyto údaje si nastavíte při <a href="/account/">registraci</a>. V rámci registrace budete mít i přednastavené služby, které jsou v současné době aktivní a u některých možnost změnit jejich nastavení pod Vaším administrátorským účtem.<br/>
   Kompletní příručka, jak zaregistrovat účet, zaktivovat služby a vytvořit první průzkum spokojenosti bude v krátké době k nalezení <a href="/sluzby/pruzkum-spokojenosti-zamestnancu/prirucka/">zde</a>.
 </p>
</article>
